{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOT5vqK/SuZHjAvPRZP66ej",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Yann-Xavier/Python/blob/main/Calculadora%20e%20conversor.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Constantes\n",
        "OPERACOES = {\n",
        "    '+': lambda x, y: x + y,\n",
        "    '-': lambda x, y: x - y,\n",
        "    '*': lambda x, y: x * y,\n",
        "    '/': lambda x, y: x / y\n",
        "}\n",
        "\n",
        "# Funções de conversão (não definidas no código fornecido)\n",
        "def decimal_para_binario(numero):\n",
        "    return bin(numero)[2:]\n",
        "\n",
        "def decimal_para_octal(numero):\n",
        "    return oct(numero)[2:]\n",
        "\n",
        "def decimal_para_hexadecimal(numero):\n",
        "    return hex(numero)[2:]\n",
        "\n",
        "def binario_para_decimal(numero):\n",
        "    return int(numero, 2)\n",
        "\n",
        "def octal_para_decimal(numero):\n",
        "    return int(numero, 8)\n",
        "\n",
        "def hexadecimal_para_decimal(numero):\n",
        "    return int(numero, 16)\n",
        "\n",
        "CONVERSOES = {\n",
        "    'D': {\n",
        "        '1': decimal_para_binario,\n",
        "        '2': decimal_para_octal,\n",
        "        '3': decimal_para_hexadecimal\n",
        "    },\n",
        "    'B': binario_para_decimal,\n",
        "    'O': octal_para_decimal,\n",
        "    'H': hexadecimal_para_decimal\n",
        "}\n",
        "\n",
        "def ler_numero(mensagem):\n",
        "    while True:\n",
        "        try:\n",
        "            numero = float(input(mensagem))\n",
        "            return numero\n",
        "        except ValueError:\n",
        "            print(\"Ops! Por favor, insira um número válido.\")\n",
        "\n",
        "def ler_operacao_conversao():\n",
        "    while True:\n",
        "        operacao = input('''\n",
        "Por favor, digite a operação matemática ou a conversão que deseja realizar:\n",
        "+ para adição\n",
        "- para subtração\n",
        "* para multiplicação\n",
        "/ para divisão\n",
        "D para converter decimal em binário, octal ou hexadecimal\n",
        "B para converter binário em decimal\n",
        "O para converter octal em decimal\n",
        "H para converter hexadecimal em decimal\n",
        "''').upper()\n",
        "\n",
        "        if operacao in OPERACOES or operacao in CONVERSOES:\n",
        "            return operacao\n",
        "        else:\n",
        "            print(\"Operação inválida!\")\n",
        "\n",
        "def calcular():\n",
        "    try:\n",
        "        operacao = ler_operacao_conversao()\n",
        "\n",
        "        if operacao in CONVERSOES:\n",
        "            if operacao == 'D':\n",
        "                numero = ler_numero('Digite o número decimal que deseja converter: ')\n",
        "                opcao = input('''\n",
        "Escolha a base de conversão:\n",
        "1 para binário\n",
        "2 para octal\n",
        "3 para hexadecimal\n",
        "''')\n",
        "\n",
        "                if opcao in CONVERSOES['D']:\n",
        "                    print(\"O número convertido é: \", CONVERSOES['D'][opcao](int(numero)))\n",
        "                else:\n",
        "                    print(\"Opção inválida!\")\n",
        "            else:\n",
        "                numero = ler_numero('Digite o número que deseja converter em decimal: ')\n",
        "                print(\"O número convertido é: \", CONVERSOES[operacao](numero))\n",
        "        else:\n",
        "            numero_1 = ler_numero('Digite seu primeiro número: ')\n",
        "            numero_2 = ler_numero('Digite seu segundo número: ')\n",
        "\n",
        "            if operacao == '+':\n",
        "                resultado = OPERACOES[operacao](numero_1, numero_2)\n",
        "                print(\"O resultado é: \", resultado)\n",
        "            elif operacao == '-':\n",
        "                resultado = OPERACOES[operacao](numero_1, numero_2)\n",
        "                print(\"O resultado é: \", resultado)\n",
        "            elif operacao == '*':\n",
        "                resultado = OPERACOES[operacao](numero_1, numero_2)\n",
        "                print(\"O resultado é: \", resultado)\n",
        "            elif operacao == '/':\n",
        "                try:\n",
        "                    resultado = OPERACOES[operacao](numero_1, numero_2)\n",
        "                    print(\"O resultado é: \", resultado)\n",
        "                except ZeroDivisionError:\n",
        "                    print(\"Não é possível dividir por zero!\")\n",
        "            else:\n",
        "                print(\"Operação inválida!\")\n",
        "\n",
        "    except Exception as e:\n",
        "        print(\"Ops! Algo deu errado.\", e)\n",
        "\n",
        "# Defina novamente() fora da função calcular()\n",
        "def novamente():\n",
        "    calc_novamente = input('''\n",
        "Deseja calcular novamente?\n",
        "Por favor, digite S para SIM ou N para NÃO.\n",
        "''')\n",
        "\n",
        "    if calc_novamente.upper() == 'S':\n",
        "        calcular()\n",
        "    elif calc_novamente.upper() == 'N':\n",
        "        print('Até logo.')\n",
        "    else:\n",
        "        novamente()\n",
        "\n",
        "calcular()\n"
      ],
      "metadata": {
        "id": "3g1p2F2jBsMl",
        "outputId": "27273540-d205-4148-f715-ea431a1b3603",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Por favor, digite a operação matemática ou a conversão que deseja realizar:\n",
            "+ para adição\n",
            "- para subtração\n",
            "* para multiplicação\n",
            "/ para divisão\n",
            "D para converter decimal em binário, octal ou hexadecimal\n",
            "B para converter binário em decimal\n",
            "O para converter octal em decimal\n",
            "H para converter hexadecimal em decimal\n",
            "D\n",
            "Digite o número decimal que deseja converter: 25101988\n",
            "\n",
            "Escolha a base de conversão:\n",
            "1 para binário\n",
            "2 para octal\n",
            "3 para hexadecimal\n",
            "3\n",
            "O número convertido é:  17f06a4\n"
          ]
        }
      ]
    }
  ]
}
